typography_spectrum: 0.6780623809900135
content_rating:
  adult: true
color:
  brandStrength: 0.5130703020840883
  lightness: 0.6858091466128826
  saturation: 0.22827284154482186
  rhythmicContrast: 0.9235421409830451
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.6719200368970633
author:
  name: cameron neale
  email: camneale@gmail.com
  url: thegrid.ai/cam
logo: null
name: shutter
title: frothingyouth
